using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.Text;

namespace AlexDuzik.EnumerationGenerator;

internal static class AttributeSourceTexts
{
    private static readonly Regex LineEndingsToCrLf = new("\r\n|\n|\r",  RegexOptions.Compiled);
    
    public static readonly SourceText EmbeddedAttribute = SourceText.From(LineEndingsToCrLf.Replace(
        """
        // <auto-generated/>
        namespace Microsoft.CodeAnalysis
        {
            internal sealed partial class EmbeddedAttribute : global::System.Attribute
            {
            }
        }
        """, "\r\n"), Encoding.UTF8);

    
    public static readonly SourceText EnumerationAttribute = SourceText.From(
        """
        using System;
        using Microsoft.CodeAnalysis;

        namespace AlexDuzik.EnumerationGenerator
        {
            [System.AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = false), Embedded]
            public class EnumerationAttribute : Attribute
            {
                
            }
        }
        """,
        Encoding.UTF8);
}