using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;

namespace AlexDuzik.EnumerationGenerator.Tests;

using GeneratorTest = CSharpSourceGeneratorVerifier<EnumerationSourceGenerator>;

public partial class AttributeTests
{
    [GeneratedRegex("\r\n|\n|\r")]
    private static partial Regex LineEndingsToCrLf { get; }
    
    private static readonly (Type, string, SourceText) EmbeddedAttribute = (
        typeof(EnumerationSourceGenerator),
        "Microsoft.CodeAnalysis.EmbeddedAttribute.cs",
        SourceText.From(LineEndingsToCrLf.Replace("""
        // <auto-generated/>
        namespace Microsoft.CodeAnalysis
        {
            internal sealed partial class EmbeddedAttribute : global::System.Attribute
            {
            }
        }
        """, "\r\n"), Encoding.UTF8));
    
    [Test]
    public async Task EnumerationAttribute_IsPresentInCompilation(CancellationToken cancellationToken)
    {
        Regex.Replace("", "\r\n|\r|\n", "\r\n");
        await new GeneratorTest.Test
        {
            TestState =
            {
                Sources =
                {
                    """
                    public class TestClass() 
                    {
                        // Do nothing
                    }
                    """
                }, 
                GeneratedSources =
                {
                    EmbeddedAttribute,
                    (typeof(EnumerationSourceGenerator), 
                        "EnumerationAttribute.g.cs",
                        EnumerationSourceGenerator.EnumerationAttributeText)
                },
            }, 
        }.RunAsync(cancellationToken);
    }
}