using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis.Text;

namespace AlexDuzik.EnumerationGenerator.Tests;

internal static partial class AttributeSources
{
    [GeneratedRegex("\r\n|\n|\r")]
    private static partial Regex LineEndingsToCrLf { get; }
    
    public static readonly (Type, string, SourceText) EmbeddedAttribute = (
        typeof(EnumerationSourceGenerator),
        "Microsoft.CodeAnalysis.EmbeddedAttribute.cs",
        SourceText.From(LineEndingsToCrLf.Replace(
            """
                  // <auto-generated/>
                  namespace Microsoft.CodeAnalysis
                  {
                      internal sealed partial class EmbeddedAttribute : global::System.Attribute
                      {
                      }
                  }
                  """, "\r\n"), Encoding.UTF8));

}